import "@/styles/globals.css";

import { type Metadata } from "next";

import { ReactFlowProvider } from "@xyflow/react";

export const metadata: Metadata = {
  title: "Mindmap",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
     <ReactFlowProvider>
        {children}
     </ReactFlowProvider>
    </>
  );
}